
package vistas;

import gestionbanco.Empresa;
import gestionbanco.Persona;
import static vistas.Principal.entidadesAutorizadas;
import static vistas.Principal.miscuentas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rmunoz
 */
public class CuentaEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form CuentaAhorro
     * @param parent
     * @param modal
     */
    public CuentaEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelNuevaCuenta = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelNumCuenta = new javax.swing.JPanel();
        jLabelNumCuenta = new javax.swing.JLabel();
        jTextFieldNumeroCuenta = new javax.swing.JTextField();
        jButtonComprobar = new javax.swing.JButton();
        jPanelDatosPersonales = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jPanelDatosCuenta = new javax.swing.JPanel();
        jLabelSaldoInicial = new javax.swing.JLabel();
        jTextFieldSaldoInicial = new javax.swing.JTextField();
        jLabelEuro = new javax.swing.JLabel();
        jLabeltipoMaxDes = new javax.swing.JLabel();
        jTextFieldMaxDesc = new javax.swing.JTextField();
        jLabelEuro2 = new javax.swing.JLabel();
        jLabelIntDes = new javax.swing.JLabel();
        jLabelComDes = new javax.swing.JLabel();
        jTextFieldIntDesc = new javax.swing.JTextField();
        jTextFieldComDesc = new javax.swing.JTextField();
        jLabelEuro3 = new javax.swing.JLabel();
        jLabelPorcentaje = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelEntidades = new javax.swing.JPanel();
        jButtonAsociarEntidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEntidades = new javax.swing.JTextArea();
        jTextFieldCodigoEnt = new javax.swing.JTextField();
        jLabelCodEnt = new javax.swing.JLabel();
        jTextFieldMaximoAut = new javax.swing.JTextField();
        jLabelMaxAut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Cuenta Ahorro");
        setBackground(new java.awt.Color(204, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 141, 186));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelNuevaCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNuevaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevaCuenta.setText("NUEVA CUENTA EMPRESA");

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco2.png"))); // NOI18N

        jPanelNumCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelNumCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NÚMERO DE CUENTA ASIGNADO AL NUEVO CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelNumCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumCuenta.setText("Número de cuenta");

        jTextFieldNumeroCuenta.setToolTipText("Número de cuenta");
        jTextFieldNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroCuentaKeyTyped(evt);
            }
        });

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNumCuentaLayout = new javax.swing.GroupLayout(jPanelNumCuenta);
        jPanelNumCuenta.setLayout(jPanelNumCuentaLayout);
        jPanelNumCuentaLayout.setHorizontalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButtonComprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNumCuentaLayout.setVerticalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumCuentaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComprobar)
                    .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumCuenta))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelDatosPersonales.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDatosPersonales.setToolTipText("Datos del nuevo cliente");

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setToolTipText("Nombre titular");

        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setEditable(false);
        jTextFieldApellidos.setToolTipText("Apellidos titular");

        jLabelFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaNacimiento.setText("Fecha de nacimiento");

        jDateChooserFechaNacimiento.setToolTipText("Fecha de nacimiento titular");
        jDateChooserFechaNacimiento.setDateFormatString("dd-MM-yyyy");
        jDateChooserFechaNacimiento.setEnabled(false);

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellidos)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabelFechaNacimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaNacimiento)
                    .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanelDatosCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LA NUEVA CUENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelSaldoInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicial.setText("Saldo inicial");

        jTextFieldSaldoInicial.setEditable(false);
        jTextFieldSaldoInicial.setToolTipText("Saldo Inicial nueva cuenta");
        jTextFieldSaldoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSaldoInicialKeyTyped(evt);
            }
        });

        jLabelEuro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro.setText("€");

        jLabeltipoMaxDes.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltipoMaxDes.setText("Máximo descubierto");

        jTextFieldMaxDesc.setEditable(false);
        jTextFieldMaxDesc.setToolTipText("Máximo descubierto para la cuenta");
        jTextFieldMaxDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMaxDescKeyTyped(evt);
            }
        });

        jLabelEuro2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro2.setText("€");

        jLabelIntDes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntDes.setText("Interes descubierto");

        jLabelComDes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComDes.setText("Comisión descubierto");

        jTextFieldIntDesc.setToolTipText("tipo de interés por descubierto");

        jTextFieldComDesc.setToolTipText("Comisión por descubierto");

        jLabelEuro3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro3.setText("€");

        jLabelPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPorcentaje.setText("%");

        javax.swing.GroupLayout jPanelDatosCuentaLayout = new javax.swing.GroupLayout(jPanelDatosCuenta);
        jPanelDatosCuenta.setLayout(jPanelDatosCuentaLayout);
        jPanelDatosCuentaLayout.setHorizontalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaldoInicial)
                    .addComponent(jLabelIntDes)
                    .addComponent(jLabelComDes)
                    .addComponent(jLabeltipoMaxDes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addComponent(jTextFieldSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMaxDesc)
                            .addComponent(jTextFieldComDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                                .addComponent(jTextFieldIntDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEuro2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEuro3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanelDatosCuentaLayout.setVerticalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEuro))
                    .addComponent(jLabelSaldoInicial, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMaxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEuro2))
                    .addComponent(jLabeltipoMaxDes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIntDes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIntDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPorcentaje)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComDes)
                    .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldComDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEuro3)))
                .addGap(17, 17, 17))
        );

        jButtonRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registrar datos");
        jButtonRegistrar.setToolTipText("Registrar nueva cuenta");
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanelEntidades.setBackground(new java.awt.Color(0, 141, 186));
        jPanelEntidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTIDADES AUTORIZADAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelEntidades.setForeground(new java.awt.Color(255, 255, 255));

        jButtonAsociarEntidad.setBackground(new java.awt.Color(0, 51, 102));
        jButtonAsociarEntidad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsociarEntidad.setText("Asociar entidad");
        jButtonAsociarEntidad.setEnabled(false);
        jButtonAsociarEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsociarEntidadActionPerformed(evt);
            }
        });

        jTextAreaEntidades.setEditable(false);
        jTextAreaEntidades.setColumns(20);
        jTextAreaEntidades.setRows(5);
        jTextAreaEntidades.setToolTipText("Entidades asociadas a la cuenta");
        jScrollPane1.setViewportView(jTextAreaEntidades);

        jTextFieldCodigoEnt.setEditable(false);
        jTextFieldCodigoEnt.setToolTipText("Código Entidad Asociada");
        jTextFieldCodigoEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoEntActionPerformed(evt);
            }
        });

        jLabelCodEnt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodEnt.setText("CODIGO");

        jTextFieldMaximoAut.setEditable(false);
        jTextFieldMaximoAut.setToolTipText("Máxinmo autorizado en entidad asociada");

        jLabelMaxAut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaxAut.setText("Máximo autorizado");

        javax.swing.GroupLayout jPanelEntidadesLayout = new javax.swing.GroupLayout(jPanelEntidades);
        jPanelEntidades.setLayout(jPanelEntidadesLayout);
        jPanelEntidadesLayout.setHorizontalGroup(
            jPanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEntidadesLayout.createSequentialGroup()
                        .addGroup(jPanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEntidadesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAsociarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEntidadesLayout.createSequentialGroup()
                                .addComponent(jLabelCodEnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigoEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabelMaxAut)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMaximoAut, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEntidadesLayout.setVerticalGroup(
            jPanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEntidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodEnt)
                    .addComponent(jTextFieldMaximoAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaxAut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAsociarEntidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogo)))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelNuevaCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("NUEVA CUENTA AHORRO");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
       
        numCuenta =jTextFieldNumeroCuenta.getText().trim().replace("-", "").replace(" ", "");

        if (numCuenta.length()!=20) {
                
            JOptionPane.showMessageDialog(null, "Error en el número de cuenta: debe tener viente dígitos\n"
                        + "Revise el número de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);
        }

        else if (!micuentaEmpresa.comprobarDigitosControl(numCuenta)) {
            
            JOptionPane.showMessageDialog(null, "Error en el número de cuenta: los dígitos de control no se corresponden con el número tecleado\n"
                        + "Revise el número de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);

        }else if (miscuentas.containsKey(numCuenta)){
            
             JOptionPane.showMessageDialog(null, "El número está asociado a una cuenta existente\n"
                        + "Teclee un nuevo número de cuenta");
             jTextFieldNumeroCuenta.setForeground(Color.red);
             
        } else {
            micuentaEmpresa.setNumeroCuenta(numCuenta);

            jTextFieldNumeroCuenta.setForeground(Color.BLACK);
            JOptionPane.showMessageDialog(null, "Número correcto y diponible para el nuevo cliente");
            
            jTextFieldNumeroCuenta.setEditable(false);
            jButtonComprobar.setEnabled(false);
            
            jTextFieldNombre.setEditable(true);
            jTextFieldApellidos.setEditable(true);
            jDateChooserFechaNacimiento.setEnabled(true);
            
            jTextFieldSaldoInicial.setEditable(true);
            jTextFieldMaxDesc.setEditable(true);
            jTextFieldIntDesc.setEditable(true);
            jTextFieldComDesc.setEditable(true);
            
            jTextFieldCodigoEnt.setEditable(true);
            jTextFieldMaximoAut.setEditable(true);
            jButtonAsociarEntidad.setEnabled(true);
            
            jButtonRegistrar.setEnabled(true);
            
        }
   
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        
        if (!comprobarCampos()) {
            JOptionPane.showMessageDialog(null, "Revise los campos del formulario.\n"
                    + "Complete los campos vacíos");
        } else {
            nuevoCliente.setNombre(jTextFieldNombre.getText());
            nuevoCliente.setApellidos(jTextFieldApellidos.getText());
            nuevoCliente.setFechaNacimiento(jDateChooserFechaNacimiento.getDate());
            saldoIn=Float.parseFloat(jTextFieldSaldoInicial.getText());
            maxDescubierto=Float.parseFloat(jTextFieldMaxDesc.getText());
            intDescubierto=Float.parseFloat(jTextFieldIntDesc.getText());
            comDescubierto=Float.parseFloat(jTextFieldComDesc.getText());
           
            if (!comprobarPositivo(saldoIn)) {
                jTextFieldSaldoInicial.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "El saldo debe ser positivo.\nTeclee de nuevo el saldo");
                jTextFieldSaldoInicial.setForeground(Color.black);
                jTextFieldSaldoInicial.setText("");
            }else if (!comprobarPositivo (maxDescubierto)) {
                jTextFieldMaxDesc.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "El máximo descubierto no puede ser 0 negativo.\nTeclee de nuevo la cantidad");
                jTextFieldMaxDesc.setForeground(Color.black);
                jTextFieldMaxDesc.setText("");
            }else if (!comprobarPositivo (intDescubierto)) {
                jTextFieldIntDesc.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "El interés por descubierto no puede ser 0 negativo.\nTeclee de nuevo la cantidad");
                jTextFieldIntDesc.setForeground(Color.black);
                jTextFieldIntDesc.setText("");
            }else if (!comprobarPositivo (comDescubierto)) {
                jTextFieldComDesc.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "La comisión por descubierto no puede ser 0 negativo.\nTeclee de nuevo la cantidad");
                jTextFieldComDesc.setForeground(Color.black);
                jTextFieldComDesc.setText("");
          
            }else {
                //Almacenamos los datos de la cuenta
                micuentaEmpresa.setSaldo(saldoIn);
                micuentaEmpresa.setMaximoDescubierto(maxDescubierto);
                micuentaEmpresa.setInteresDescubierto(intDescubierto);
                micuentaEmpresa.setComisionDescubierto(comDescubierto);

                miscuentas.put(numCuenta, micuentaEmpresa);
                JOptionPane.showMessageDialog(null, "Cuenta registrada correctamente");

                jTextFieldNumeroCuenta.setText("");
                jTextFieldNumeroCuenta.setEditable(true);
                jButtonComprobar.setEnabled(true);

                jTextFieldNombre.setText("");
                jTextFieldNombre.setEditable(false);
                jTextFieldApellidos.setText("");
                jTextFieldApellidos.setEditable(false);
                jDateChooserFechaNacimiento.setDate(null);
                jDateChooserFechaNacimiento.setEnabled(false);

                jTextFieldSaldoInicial.setText("");
                jTextFieldSaldoInicial.setEditable(false);
                jTextFieldMaxDesc.setText("");
                jTextFieldMaxDesc.setEditable(false);
                jTextFieldIntDesc.setText("");
                jTextFieldIntDesc.setEditable(false);
                jTextFieldComDesc.setText("");
                jTextFieldComDesc.setEditable(false);
                
                jTextFieldCodigoEnt.setEditable(false);
                jTextFieldMaximoAut.setEditable(false);
                jButtonAsociarEntidad.setEnabled(false);
                jTextAreaEntidades.setText("");
                
                jButtonRegistrar.setEnabled(false);
            }            
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed
    
    
    private void jTextFieldNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCuentaKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Sólo se admiten valores numéricos");
        }
    }//GEN-LAST:event_jTextFieldNumeroCuentaKeyTyped

    private void jTextFieldSaldoInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaldoInicialKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Sólo se admiten valores numéricos");
        }
    }//GEN-LAST:event_jTextFieldSaldoInicialKeyTyped

    private void jTextFieldMaxDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMaxDescKeyTyped
        
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Sólo se admiten valores numéricos");
        }
    }//GEN-LAST:event_jTextFieldMaxDescKeyTyped

    private void jButtonAsociarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsociarEntidadActionPerformed
       
       
       if ("".equals(jTextFieldCodigoEnt.getText()) || "".equals(jTextFieldMaximoAut.getText()) ) {
            jTextFieldMaximoAut.setBackground(Color.red);
            jTextFieldCodigoEnt.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Las entidades autorizadas deben tener un código \n"
                   + "y deben tener una cantidad máxima permitida.");
            jTextFieldMaximoAut.setBackground(Color.white);
            jTextFieldCodigoEnt.setBackground(Color.white);
           
       } else {
           cod = jTextFieldCodigoEnt.getText();
           maxAutori = Double.parseDouble(jTextFieldMaximoAut.getText());
           
            if (!comprobarPositivo (maxAutori)) {
           
                jTextFieldMaximoAut.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "El máximo autorizado debe ser positivo.\nTeclee de nuevo la cantidad");
                jTextFieldMaximoAut.setForeground(Color.black);
                jTextFieldMaximoAut.setText("");
             
            } else if (entidadesAutorizadas.containsKey(cod)){
                
                int op = JOptionPane.showConfirmDialog(null, "Ya existe una entidad almacenada con ese código.\n"
                         + "¿Desea asociar esa entidad a la cuenta bancaria actual con el máximo permitido asociado a la misma?");
                
                if (op ==0) {
                    
                    micuentaEmpresa.almacenarEntidadesPropias(cod, entidadesAutorizadas.get(cod));
                    jTextAreaEntidades.setText(misentidades.toString());
                    jTextFieldCodigoEnt.setText("");
                    jTextFieldMaximoAut.setText("");
                }
                
            } else {
               
                micuentaEmpresa.almacenarEntidadesPropias(cod, maxAutori);
                entidadesAutorizadas.put(cod, maxAutori);
              
                jTextAreaEntidades.setText(misentidades.toString());
                jTextFieldCodigoEnt.setText("");
                jTextFieldMaximoAut.setText("");
            }
       }
      
    }//GEN-LAST:event_jButtonAsociarEntidadActionPerformed

    private void jTextFieldCodigoEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoEntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CuentaEmpresa dialog = new CuentaEmpresa(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsociarEntidad;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCodEnt;
    private javax.swing.JLabel jLabelComDes;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelEuro2;
    private javax.swing.JLabel jLabelEuro3;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelIntDes;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMaxAut;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNuevaCuenta;
    private javax.swing.JLabel jLabelNumCuenta;
    private javax.swing.JLabel jLabelPorcentaje;
    private javax.swing.JLabel jLabelSaldoInicial;
    private javax.swing.JLabel jLabeltipoMaxDes;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDatosCuenta;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelEntidades;
    private javax.swing.JPanel jPanelNumCuenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEntidades;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCodigoEnt;
    private javax.swing.JTextField jTextFieldComDesc;
    private javax.swing.JTextField jTextFieldIntDesc;
    private javax.swing.JTextField jTextFieldMaxDesc;
    private javax.swing.JTextField jTextFieldMaximoAut;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroCuenta;
    private javax.swing.JTextField jTextFieldSaldoInicial;
    // End of variables declaration//GEN-END:variables

    String numCuenta;
    Persona nuevoCliente = new Persona () {};
    Date fechaNac;
    double saldoIn;
    double maxDescubierto;
    double intDescubierto;
    double comDescubierto;
    String cod;
    double maxAutori;
    double dispo;
    ArrayList misentidades = new ArrayList();


    Empresa micuentaEmpresa = new Empresa (numCuenta, nuevoCliente, saldoIn, maxDescubierto, intDescubierto, comDescubierto, misentidades);

    public boolean comprobarCampos (){
            return !("".equals(jTextFieldNombre.getText()) 
                    ||"".equals(jTextFieldApellidos.getText())
                    || jDateChooserFechaNacimiento.getDate()== null
                    || "".equals(jTextFieldSaldoInicial.getText())
                    ||"".equals(jTextFieldMaxDesc.getText())
                    );
    }
    
    public boolean comprobarPositivo (double valor) {
        return valor>0;
    }
}
