package vistas;

import gestionbanco.Bancaria;
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rmunoz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNuevosClientes = new javax.swing.JLabel();
        jButtonNuevaAhorro = new javax.swing.JButton();
        jButtonNuevaEmpresa = new javax.swing.JButton();
        jButtonNuevaCorriente = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jLabelGestiones = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonRetirar = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelLogoBanco = new javax.swing.JLabel();
        jButtonListado = new javax.swing.JButton();
        jButtonListaEntidades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(140, 22, 22));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 141, 186));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNuevosClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNuevosClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevosClientes.setText("Nuevos clientes");
        jPanel1.add(jLabelNuevosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, -1));

        jButtonNuevaAhorro.setBackground(new java.awt.Color(153, 0, 51));
        jButtonNuevaAhorro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevaAhorro.setText("CUENTA AHORRO");
        jButtonNuevaAhorro.setToolTipText("Alta nueva cuenta Ahorro");
        jButtonNuevaAhorro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNuevaAhorro.setDefaultCapable(false);
        jButtonNuevaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaAhorroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 110));

        jButtonNuevaEmpresa.setBackground(new java.awt.Color(255, 0, 102));
        jButtonNuevaEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevaEmpresa.setText("CUENTA EMPRESA");
        jButtonNuevaEmpresa.setToolTipText("Alta nueva cuenta corriente Empresa");
        jButtonNuevaEmpresa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNuevaEmpresa.setDefaultCapable(false);
        jButtonNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, 110));

        jButtonNuevaCorriente.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNuevaCorriente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevaCorriente.setText("CUENTA CORRIENTE");
        jButtonNuevaCorriente.setToolTipText("Alta nueva cuenta corriente Personal");
        jButtonNuevaCorriente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNuevaCorriente.setDefaultCapable(false);
        jButtonNuevaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaCorrienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevaCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 150, 110));
        jPanel1.add(jSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 850, 10));

        jLabelGestiones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGestiones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestiones.setText("Gestiones");
        jPanel1.add(jLabelGestiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, -1));

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setToolTipText("Realizar un ingreso");
        jButtonIngresar.setBorder(null);
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 50));

        jButtonRetirar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRetirar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRetirar.setText("Retirar fondos");
        jButtonRetirar.setToolTipText("Realizar un reintegro");
        jButtonRetirar.setBorder(null);
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, 50));

        jButtonSaldo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaldo.setText("Consultar saldo");
        jButtonSaldo.setToolTipText("Consulta de saldo");
        jButtonSaldo.setBorder(null);
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, 50));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 110, 40));

        jLabelLogoBanco.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabelLogoBanco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco.png"))); // NOI18N
        jPanel1.add(jLabelLogoBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 170, 140));

        jButtonListado.setBackground(new java.awt.Color(0, 0, 0));
        jButtonListado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListado.setText("Listar cuentas");
        jButtonListado.setToolTipText("Ver lista de cuentas");
        jButtonListado.setBorder(null);
        jButtonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 140, 50));

        jButtonListaEntidades.setBackground(new java.awt.Color(0, 0, 0));
        jButtonListaEntidades.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListaEntidades.setText("Entidades Autorizadas");
        jButtonListaEntidades.setToolTipText("Ver lista de entidades autorizadas");
        jButtonListaEntidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaEntidadesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonListaEntidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonNuevaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaAhorroActionPerformed
        
        CuentaAhorro miAhorro = new CuentaAhorro (null, true);
        miAhorro.setVisible(true);
    }//GEN-LAST:event_jButtonNuevaAhorroActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        Ingreso miingreso = new Ingreso (null, true);
        miingreso.setVisible(true); 
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        // TODO add your handling code here:
        ConsultarSaldo miconsulta = new ConsultarSaldo (null, true);
        miconsulta.setVisible (true);
        
    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        // TODO add your handling code here:
        Reintegro mireintegro = new Reintegro (null, true);
        mireintegro.setVisible(true);
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    private void jButtonNuevaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaCorrienteActionPerformed
        // TODO add your handling code here:
        CuentaPersonal micuentaCorrientePersonal = new CuentaPersonal (null, true);
        micuentaCorrientePersonal.setVisible(true);
    }//GEN-LAST:event_jButtonNuevaCorrienteActionPerformed

    private void jButtonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoActionPerformed
        ListadoCuentas milistado = new ListadoCuentas(null, true);
        milistado.setVisible(true);
    }//GEN-LAST:event_jButtonListadoActionPerformed

    private void jButtonListaEntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaEntidadesActionPerformed
        ListadoEntidades milistadoEntidades = new ListadoEntidades (null, true);
        milistadoEntidades.setVisible(true);
    }//GEN-LAST:event_jButtonListaEntidadesActionPerformed

    private void jButtonNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaEmpresaActionPerformed
        // TODO add your handling code here:
        CuentaEmpresa micuentaEmpresa = new CuentaEmpresa (null, true);
        micuentaEmpresa.setVisible(true);
    }//GEN-LAST:event_jButtonNuevaEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonListaEntidades;
    private javax.swing.JButton jButtonListado;
    private javax.swing.JButton jButtonNuevaAhorro;
    private javax.swing.JButton jButtonNuevaCorriente;
    private javax.swing.JButton jButtonNuevaEmpresa;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelGestiones;
    private javax.swing.JLabel jLabelLogoBanco;
    private javax.swing.JLabel jLabelNuevosClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator;
    // End of variables declaration//GEN-END:variables

    static HashMap <String, Bancaria> miscuentas = new HashMap<>();
    static HashMap <String, Double> entidadesAutorizadas = new HashMap<>();
}
