package vistas;

import gestionbanco.Bancaria;
import static vistas.Principal.miscuentas;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rmunoz
 */
public class Reintegro extends javax.swing.JDialog {

    /**
     * Creates new form CuentaAhorro
     *
     * @param parent
     * @param modal
     */
    public Reintegro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelNuevaCuenta = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelNumCuenta = new javax.swing.JPanel();
        jLabelNumCuenta = new javax.swing.JLabel();
        jTextFieldNumeroCuenta = new javax.swing.JTextField();
        jButtonComprobar = new javax.swing.JButton();
        jPanelDatosPersonales = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelSaldoInicial1 = new javax.swing.JLabel();
        jTextFieldSaldoActual = new javax.swing.JTextField();
        jLabelEuro1 = new javax.swing.JLabel();
        jLabelAvisoDescubierto = new javax.swing.JLabel();
        jPanelDatosCuenta = new javax.swing.JPanel();
        jTextFieldReintegro = new javax.swing.JTextField();
        jLabelEuro = new javax.swing.JLabel();
        errorInteres = new javax.swing.JLabel();
        errorCantidad = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelDatosCuenta1 = new javax.swing.JPanel();
        errorInteres1 = new javax.swing.JLabel();
        jTextFieldSaldoFinal = new javax.swing.JTextField();
        jLabelEuro4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Cuenta Ahorro");
        setBackground(new java.awt.Color(204, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 141, 186));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelNuevaCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNuevaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevaCuenta.setText("GESTION DE REINTEGROS");

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco2.png"))); // NOI18N

        jPanelNumCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelNumCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NÚMERO DE CUENTA PARA REALIZAR EL INGRESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelNumCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumCuenta.setText("Número de cuenta");

        jTextFieldNumeroCuenta.setToolTipText("Número de cuenta");
        jTextFieldNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroCuentaKeyTyped(evt);
            }
        });

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNumCuentaLayout = new javax.swing.GroupLayout(jPanelNumCuenta);
        jPanelNumCuenta.setLayout(jPanelNumCuentaLayout);
        jPanelNumCuentaLayout.setHorizontalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumCuentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonComprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNumCuentaLayout.setVerticalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumCuentaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumCuenta)
                    .addComponent(jButtonComprobar))
                .addContainerGap())
        );

        jPanelDatosPersonales.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TITULAR Y SALDO ACTUAL DE LA CUENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDatosPersonales.setToolTipText("TITULAR DE LA CUENTA");

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setToolTipText("Nombre del titular");

        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setEditable(false);
        jTextFieldApellidos.setToolTipText("Apellidos del titular");

        jLabelSaldoInicial1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicial1.setText("Disponible");

        jTextFieldSaldoActual.setEditable(false);
        jTextFieldSaldoActual.setToolTipText("Saldo actual de la cuenta");

        jLabelEuro1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro1.setText("€");

        jLabelAvisoDescubierto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelAvisoDescubierto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAvisoDescubierto.setText("*Se incluye el descubierto disponible en caso de cuenta empresa");

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidos)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelSaldoInicial1))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEuro1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAvisoDescubierto))
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEuro1)
                    .addComponent(jLabelSaldoInicial1)
                    .addComponent(jLabelAvisoDescubierto))
                .addGap(15, 15, 15))
        );

        jPanelDatosCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CANTIDAD A RETIRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextFieldReintegro.setEditable(false);
        jTextFieldReintegro.setToolTipText("Cantidad a retirar");
        jTextFieldReintegro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldReintegroKeyTyped(evt);
            }
        });

        jLabelEuro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro.setText("€");

        errorInteres.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        errorInteres.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelDatosCuentaLayout = new javax.swing.GroupLayout(jPanelDatosCuenta);
        jPanelDatosCuenta.setLayout(jPanelDatosCuentaLayout);
        jPanelDatosCuentaLayout.setHorizontalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(errorInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldReintegro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosCuentaLayout.setVerticalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEuro)
                        .addComponent(jTextFieldReintegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(errorInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("REALIZAR REINTEGRO");
        jButtonRegistrar.setToolTipText("Realizar el reintegro");
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanelDatosCuenta1.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosCuenta1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALDO RESULTANTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        errorInteres1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        errorInteres1.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldSaldoFinal.setEditable(false);
        jTextFieldSaldoFinal.setBackground(new java.awt.Color(0, 99, 182));
        jTextFieldSaldoFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSaldoFinal.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSaldoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSaldoFinal.setToolTipText("Saldo resultante después de la operación");
        jTextFieldSaldoFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelEuro4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEuro4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro4.setText("€");

        javax.swing.GroupLayout jPanelDatosCuenta1Layout = new javax.swing.GroupLayout(jPanelDatosCuenta1);
        jPanelDatosCuenta1.setLayout(jPanelDatosCuenta1Layout);
        jPanelDatosCuenta1Layout.setHorizontalGroup(
            jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEuro4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanelDatosCuenta1Layout.setVerticalGroup(
            jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEuro4))
                .addGap(23, 23, 23)
                .addComponent(errorInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalir))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabelNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabelLogo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelNuevaCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButtonSalir)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("NUEVA CUENTA AHORRO");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed

        numCuenta = jTextFieldNumeroCuenta.getText().trim().replace("-", "").replace(" ", "");

        //Comprobamos la longitud del número de cuenta (20 dígitos)
        if (numCuenta.length() != 20) {

            JOptionPane.showMessageDialog(null, "Error en el número de cuenta: debe tener viente dígitos\n"
                    + "Revise el número de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);
        } //Comprobación de los dígitos de control
        else if (!micuenta.comprobarDigitosControl(numCuenta)) {

            JOptionPane.showMessageDialog(null, "Error en el número de cuenta: los dígitos de control no se corresponden con el número tecleado\n"
                    + "Revise el número de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);

            // Comprobamos que el número de cuenta no está ya en uso
        } else if (!miscuentas.containsKey(numCuenta)) {

            System.out.println("No existe ninguna cuenta asociada a ese número");
            // JOptionPane.showMessageDialog(null, "No existe ninguna cuenta asociada a ese número");

        } else {
            if (miscuentas.containsKey(numCuenta)) {

                jTextFieldNumeroCuenta.setForeground(Color.BLACK);

                jTextFieldNombre.setText(miscuentas.get(numCuenta).getCliente().getNombre());
                jTextFieldApellidos.setText(miscuentas.get(numCuenta).getCliente().getApellidos());
                jTextFieldSaldoActual.setText(String.valueOf(miscuentas.get(numCuenta).getDisponible()));
                jTextFieldReintegro.setEditable(true);
                jButtonRegistrar.setEnabled(true);
                jTextFieldNumeroCuenta.setEditable(false);
                jButtonComprobar.setEnabled(false);

            }
        }

    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed

        reintegro = Double.parseDouble(jTextFieldReintegro.getText());
        cantidadDisponible = miscuentas.get(numCuenta).getDisponible();

        if (reintegro > cantidadDisponible) {
            JOptionPane.showMessageDialog(null, "La cantidad a retirar supera el disponible. Teclee otra cantidad.\n"
                    + "Disponible: " + cantidadDisponible + " €");
            jTextFieldReintegro.setForeground(Color.red);
        } else {
            cantidadDisponible = miscuentas.get(numCuenta).reintegro(reintegro);
            jTextFieldSaldoFinal.setText(String.valueOf(miscuentas.get(numCuenta).getSaldo()));

            if (miscuentas.get(numCuenta).getSaldo() < 0) {
                jTextFieldSaldoFinal.setForeground(Color.RED);
            }
            JOptionPane.showMessageDialog(null, "Reintegro realizado correctamente");

            // Reiniciamos el formulario
            jTextFieldNumeroCuenta.setText("");
            jTextFieldNumeroCuenta.setEditable(true);
            jButtonComprobar.setEnabled(true);

            jTextFieldNombre.setText("");
            jTextFieldApellidos.setText("");
            jTextFieldSaldoActual.setText("");

            jTextFieldReintegro.setText("");
            jTextFieldReintegro.setEditable(false);

            jTextFieldSaldoFinal.setText("");

            jButtonRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        dispose();

    }//GEN-LAST:event_jButtonSalirActionPerformed


    private void jTextFieldNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCuentaKeyTyped

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldNumeroCuentaKeyTyped

    private void jTextFieldReintegroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReintegroKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Sólo se admiten valores numéricos");
        }
    }//GEN-LAST:event_jTextFieldReintegroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reintegro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reintegro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reintegro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reintegro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reintegro dialog = new Reintegro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorCantidad;
    private javax.swing.JLabel errorInteres;
    private javax.swing.JLabel errorInteres1;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelAvisoDescubierto;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelEuro1;
    private javax.swing.JLabel jLabelEuro4;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNuevaCuenta;
    private javax.swing.JLabel jLabelNumCuenta;
    private javax.swing.JLabel jLabelSaldoInicial1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDatosCuenta;
    private javax.swing.JPanel jPanelDatosCuenta1;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelNumCuenta;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroCuenta;
    private javax.swing.JTextField jTextFieldReintegro;
    private javax.swing.JTextField jTextFieldSaldoActual;
    private javax.swing.JTextField jTextFieldSaldoFinal;
    // End of variables declaration//GEN-END:variables

    String numCuenta;
    double cantidadDisponible;
    double reintegro;

    Bancaria micuenta = new Bancaria();

    public boolean comprobarCampos() {
        return !("".equals(jTextFieldReintegro.getText()));
    }

    public boolean comprobarPositivo(double valor) {
        return valor > 0;
    }

}
