
package HR_vistas;

import HR_gestionbanco.HR_Bancaria;
import static HR_vistas.HR_Principal.miscuentas;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author hruiz
 */
public class HR_Ingreso extends javax.swing.JDialog {

    /**
     * Creates new form CuentaAhorro
     * @param parent
     * @param modal
     */
    public HR_Ingreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelNuevaCuenta = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelNumCuenta = new javax.swing.JPanel();
        jLabelNumCuenta = new javax.swing.JLabel();
        jTextFieldNumeroCuenta = new javax.swing.JTextField();
        jButtonComprobar = new javax.swing.JButton();
        jPanelDatosPersonales = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelSaldoInicial1 = new javax.swing.JLabel();
        jTextFieldSaldoActual = new javax.swing.JTextField();
        jLabelEuro1 = new javax.swing.JLabel();
        jPanelDatosCuenta = new javax.swing.JPanel();
        jTextFieldIngreso = new javax.swing.JTextField();
        jLabelEuro = new javax.swing.JLabel();
        errorInteres = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelDatosCuenta1 = new javax.swing.JPanel();
        errorInteres1 = new javax.swing.JLabel();
        jTextFieldSaldoFinal = new javax.swing.JTextField();
        jLabelEuro4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Cuenta Ahorro");
        setBackground(new java.awt.Color(204, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 141, 186));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelNuevaCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNuevaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevaCuenta.setText("GESTION DE INGRESOS");

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco2.png"))); // NOI18N

        jPanelNumCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelNumCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NÚMERO DE CUENTA PARA REALIZAR EL INGRESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelNumCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumCuenta.setText("Número de cuenta");

        jTextFieldNumeroCuenta.setToolTipText("Número de cuenta");
        jTextFieldNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroCuentaKeyTyped(evt);
            }
        });

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNumCuentaLayout = new javax.swing.GroupLayout(jPanelNumCuenta);
        jPanelNumCuenta.setLayout(jPanelNumCuentaLayout);
        jPanelNumCuentaLayout.setHorizontalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumCuentaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelNumCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonComprobar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelNumCuentaLayout.setVerticalGroup(
            jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumCuentaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelNumCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumCuenta)
                    .addComponent(jButtonComprobar))
                .addContainerGap())
        );

        jPanelDatosPersonales.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TITULAR Y SALDO ACTUAL DE LA CUENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDatosPersonales.setToolTipText("TITULAR DE LA CUENTA");

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setToolTipText("Nombre del titular");

        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setEditable(false);
        jTextFieldApellidos.setToolTipText("Apellidos del titular");

        jLabelSaldoInicial1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicial1.setText("Saldo actual");

        jTextFieldSaldoActual.setEditable(false);
        jTextFieldSaldoActual.setToolTipText("Fecha de nacimiento del titular");

        jLabelEuro1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro1.setText("€");

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidos)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelSaldoInicial1))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEuro1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEuro1)
                    .addComponent(jLabelSaldoInicial1))
                .addGap(15, 15, 15))
        );

        jPanelDatosCuenta.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CANTIDAD A INGRESAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextFieldIngreso.setEditable(false);
        jTextFieldIngreso.setToolTipText("Cantidad a ingresar");
        jTextFieldIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIngresoKeyTyped(evt);
            }
        });

        jLabelEuro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro.setText("€");

        errorInteres.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        errorInteres.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelDatosCuentaLayout = new javax.swing.GroupLayout(jPanelDatosCuenta);
        jPanelDatosCuenta.setLayout(jPanelDatosCuentaLayout);
        jPanelDatosCuentaLayout.setHorizontalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(errorInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosCuentaLayout.setVerticalGroup(
            jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEuro)
                    .addComponent(jTextFieldIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("REALIZAR INGRESO");
        jButtonRegistrar.setToolTipText("Realizar ingreso en la cuenta");
        jButtonRegistrar.setEnabled(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanelDatosCuenta1.setBackground(new java.awt.Color(0, 141, 186));
        jPanelDatosCuenta1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALDO RESULTANTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        errorInteres1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        errorInteres1.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldSaldoFinal.setEditable(false);
        jTextFieldSaldoFinal.setBackground(new java.awt.Color(0, 99, 182));
        jTextFieldSaldoFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSaldoFinal.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSaldoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSaldoFinal.setToolTipText("Saldo resultante");
        jTextFieldSaldoFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelEuro4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEuro4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEuro4.setText("€");

        javax.swing.GroupLayout jPanelDatosCuenta1Layout = new javax.swing.GroupLayout(jPanelDatosCuenta1);
        jPanelDatosCuenta1.setLayout(jPanelDatosCuenta1Layout);
        jPanelDatosCuenta1Layout.setHorizontalGroup(
            jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEuro4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanelDatosCuenta1Layout.setVerticalGroup(
            jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEuro4))
                .addGap(25, 25, 25)
                .addComponent(errorInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalir))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabelNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabelLogo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelNuevaCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButtonSalir)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("NUEVA CUENTA AHORRO");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
       
        numCuenta =jTextFieldNumeroCuenta.getText().trim().replace("-", "").replace(" ", "");

        if (numCuenta.length()!=20) {
                
            JOptionPane.showMessageDialog(null, "Error en el nï¿½mero de cuenta: debe tener viente dï¿½gitos\n"
                        + "Revise el nï¿½mero de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);
        }

        else if (!micuenta.comprobarDigitosControl(numCuenta)) {
            
            JOptionPane.showMessageDialog(null, "Error en el nï¿½mero de cuenta: los dï¿½gitos de control no se corresponden con el nï¿½mero tecleado\n"
                        + "Revise el nï¿½mero de cuenta.");
            jTextFieldNumeroCuenta.setForeground(Color.red);

        }else if (!miscuentas.containsKey(numCuenta)){
            
             JOptionPane.showMessageDialog(null, "No existe ninguna cuenta asociada a ese nï¿½mero");
             
             
        } else {
            if (miscuentas.containsKey(numCuenta)) {
            
            jTextFieldNumeroCuenta.setForeground(Color.BLACK);
            
            jTextFieldNombre.setText(miscuentas.get(numCuenta).getCliente().getNombre());
            jTextFieldApellidos.setText(miscuentas.get(numCuenta).getCliente().getApellidos());
            jTextFieldApellidos.setText(miscuentas.get(numCuenta).getCliente().getApellidos());
            jTextFieldSaldoActual.setText(String.valueOf(miscuentas.get(numCuenta).getSaldo()));
            jTextFieldIngreso.setEditable(true);
            jButtonRegistrar.setEnabled(true);
            jTextFieldNumeroCuenta.setEditable(false);
            jButtonComprobar.setEnabled(false);
            
            }
        }
   
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
          

        if (!comprobarCampos()) {
            JOptionPane.showMessageDialog(null, "Debe completar el campo Cantidad a ingresar");
        }else {
            cantidadIngreso = Double.parseDouble(jTextFieldIngreso.getText());
            
            if (!comprobarPositivo(cantidadIngreso)) {
                jTextFieldIngreso.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "La cantidad a ingresar debe ser positiva.\nTeclee de nuevo la cantidad");
                jTextFieldIngreso.setForeground(Color.black);
                jTextFieldIngreso.setText("");
            } else {
                cantidadIngreso = Double.parseDouble(jTextFieldIngreso.getText());
                micuenta.setCantidadIngresada(cantidadIngreso);
                saldoIn = Double.parseDouble(jTextFieldSaldoActual.getText());
                micuenta.setSaldo(saldoIn);

                miscuentas.get(numCuenta).setSaldo(micuenta.ingresar(cantidadIngreso));

                jTextFieldSaldoFinal.setText(String.valueOf(miscuentas.get(numCuenta).getSaldo()));

                JOptionPane.showMessageDialog(null, "Ingreso realizado correctamente");
                
                this.dispose();

            }
        }     
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       
        dispose();
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCuentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Sï¿½lo se admiten valores numï¿½ricos");
        }
    }//GEN-LAST:event_jTextFieldNumeroCuentaKeyTyped

    private void jTextFieldIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIngresoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Sï¿½lo se admiten valores numï¿½ricos");
        }
    }//GEN-LAST:event_jTextFieldIngresoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HR_Ingreso dialog = new HR_Ingreso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorInteres;
    private javax.swing.JLabel errorInteres1;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelEuro1;
    private javax.swing.JLabel jLabelEuro4;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNuevaCuenta;
    private javax.swing.JLabel jLabelNumCuenta;
    private javax.swing.JLabel jLabelSaldoInicial1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDatosCuenta;
    private javax.swing.JPanel jPanelDatosCuenta1;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelNumCuenta;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldIngreso;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroCuenta;
    private javax.swing.JTextField jTextFieldSaldoActual;
    private javax.swing.JTextField jTextFieldSaldoFinal;
    // End of variables declaration//GEN-END:variables



String error ="El campo no puede quedar vacï¿½o";
String errorNegativo ="El valor debe ser mayor que 0";
String numCuenta;
double saldoIn;
double cantidadIngreso;

HR_Bancaria micuenta = new HR_Bancaria ();

 public boolean comprobarCampos (){
            return !("".equals(jTextFieldIngreso.getText()));
    }

public boolean comprobarPositivo (double valor) {
        return valor>0;
    }

}
